### PR TITLE
some general code care

### PR DESCRIPTION
**Pull request by hoba87**
no functional changes, only 
 - sorting imports
 - replacing deprecated distutils.version
 - loosening matplotlib and kivy requirements
 - pytest deprectation warnings only for this package

### CODE REVIEW

**Review by AndreMiras — COMMENTED** [review]
I have nothing against code formatters like black or isort, but then should it not be part of the repo & CI.
That way we know what formatter was used, what ruling and we are sure things don't get messed up with on the next pull requests?

**Comment by hoba87** [comment]
I have added isort and black configuration settings and according changes of code formatting

**Comment by AndreMiras** [comment]
Thanks for looking this up :muscle: 
This is more changes than I initially expected after introducing the formatter.
I don't have anything against black myself as I use for my personal projects, but I know it's a contentious topic in Kivy.
So I wanted to let the PR open a little bit to see if anyone would chime in.
Tehn I saw some of the recent  commit from misl6 was actually running black (7864a8e), so I guess we're good.
After merging that PR, it could be nice to have a follow up for adding format checks from the CI

**Review by AndreMiras — APPROVED** [review]
LGTM

**Pull request merged**
